version: '3.5'
services:
    solar_limp_database:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: solar_limp
            MYSQL_USER: guilherme
            MYSQL_PASSWORD: guilherme
        volumes:
            - ./.data/mysql:/var/lib/mysql
